# -*- coding: utf-8 -*-
"""logu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_ohVNuWUA_vZw4dDLZzLwqfKfe_9oEk
"""

!pip install deepface opencv-python-headless vaderSentiment ipywidgets

import cv2
from deepface import DeepFace
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from IPython.display import display, HTML, clear_output
import ipywidgets as widgets
import tempfile
import os
from google.colab import files
import shutil

# Initialize sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

def analyze_text_sentiment(text):
    score = analyzer.polarity_scores(text)
    if score['compound'] >= 0.05:
        return 'Positive 😀'
    elif score['compound'] <= -0.05:
        return 'Negative 😞'
    else:
        return 'Neutral 😐'

def analyze_video_emotion(video_path):
    cap = cv2.VideoCapture(video_path)
    ret, frame = cap.read()
    cap.release()

    if ret:
        try:
            analysis = DeepFace.analyze(frame, actions=['emotion'], enforce_detection=False)
            return analysis[0]['dominant_emotion'].capitalize()
        except Exception as e:
            return f"Emotion detection failed: {str(e)}"
    else:
        return "Could not read the video file."

# Text post input box
text_area = widgets.Textarea(
    value='',
    placeholder='Type your post here...',
    description='Post:',
    layout=widgets.Layout(width='100%', height='100px')
)

# Upload video button
upload_button = widgets.FileUpload(
    accept='video/*',
    multiple=False,
    description='Upload Video'
)

# Analyze button
analyze_button = widgets.Button(description="Analyze Post", button_style='success')
output_box = widgets.Output()

# Event handler
def on_analyze_clicked(b):
    with output_box:
        clear_output()

        # Analyze text
        text = text_area.value
        if text.strip() != "":
            sentiment = analyze_text_sentiment(text)
            print(f"Text Sentiment: {sentiment}")
        else:
            print("No text provided.")

        # Analyze video
        if upload_button.value:
            uploaded_file = list(upload_button.value.values())[0]
            temp_video_path = os.path.join(tempfile.gettempdir(), uploaded_file['metadata']['name'])
            with open(temp_video_path, 'wb') as f:
                f.write(uploaded_file['content'])

            emotion = analyze_video_emotion(temp_video_path)
            print(f"Video Emotion: {emotion}")
        else:
            print("No video uploaded.")

analyze_button.on_click(on_analyze_clicked)

display(HTML("<h2>📱 Social Media Post Emotion & Sentiment Analyzer</h2>"))
display(text_area)
display(upload_button)
display(analyze_button)
display(output_box)